### ISSUE TITLE
`ClashStrategy::PrioritizeLongest` changed its behavior and no longer clears actions

### ISSUE THREAD

**Issue by porkbrain** [Leafwing-Studios/leafwing-input-manager#471] opened 2024-02-19 16:07 UTC
## Version

`0.12.0`

## What you did

I query the `ActionState` resource with: `controls: Res<ActionState<GlobalAction>>`.

Simplified, my `GlobalAction` looks like this:
```rust
#[derive(
    Actionlike, PartialEq, Eq, Hash, Clone, Copy, Debug, Reflect, EnumIter,
)]
pub enum GlobalAction {
    /// Going only up.
    MoveUp,
    /// Going only left.
    MoveLeft,
    /// Going both up and left.
    /// Overwrites `MoveUp` and `MoveLeft`.
    MoveUpLeft,
}
```

In prior version, `controls.get_pressed().last()` would return `MoveUpLeft` if I help both Up and Left. After upgrading, the `controls.get_pressed()` vector contains two actions: the `MoveUpLeft` and either `MoveLeft` or `MoveUp`. Sometimes `MoveUp`/`MoveLeft` is on index 0, sometimes on index 1. 

I'd expect that when I press the combination of `MoveUpLeft`, `MoveUp` nor `MoveLeft` would be emitted.

Some additional info about how I map the inputs:

```rust

impl GlobalAction {
    fn input_map() -> InputMap<Self> {
        let mut input_map = InputMap::default();

        for action in GlobalAction::iter() {
            for input in GlobalAction::default_keyboard_input(action) {
                input_map.insert(action, input);
            }
        }

        input_map
    }

    fn default_keyboard_input(action: GlobalAction) -> Vec<UserInput> {
        use InputKind::Keyboard as Kbd;
        use KeyCode as Key;
        use UserInput::{Chord, Single};

        match action {
            Self::MoveLeft => {
                vec![Single(Kbd(Key::A)), Single(Kbd(Key::Left))]
            }
            Self::MoveUp => {
                vec![Single(Kbd(Key::W)), Single(Kbd(Key::Up))]
            }
            Self::MoveUpLeft => vec![
                Chord(vec![Kbd(Key::W), Kbd(Key::A)]),
                Chord(vec![Kbd(Key::Up), Kbd(Key::Left)]),
            ],
        }
    }
}
```

**Comment by alice-i-cecile** [comment] 2024-02-19 16:22
Thanks for the report! There was a number of complex refactors and our test coverage must have been lacking.

**Comment by Shute052** [comment] 2024-02-19 16:33
#466 should not changing those behaviors, could this issue have originated from older commits?

**Comment by Shute052** [comment] 2024-02-19 16:56
> In prior version, `controls.get_pressed().last()` would return `MoveUpLeft` if I help both Up and Left. After upgrading, the `controls.get_pressed()` vector contains two actions: the `MoveUpLeft` and either `MoveLeft` or `MoveUp`. Sometimes `MoveUp`/`MoveLeft` is on index 0, sometimes on index 1.

This issue seems to have been caused by #450, but it was actually committed by #452, which replaced the use of `Vec` with `HashMap` to store `ActionData`. However, `HashMap` does not guarantee the order when collecting its values.

## Relevant Code
```rust
// Before
pub fn get_pressed(&self) -> Vec<A> {
    A::variants().filter(|a| self.pressed(a)).collect()
}

// After
pub fn get_pressed(&self) -> Vec<A> {
    self.action_data
        .iter()
        .filter(|(_action, data)| data.state.pressed())
        .map(|(action, _data)| action.clone())
        .collect()
}
```

**Comment by Shute052** [comment] 2024-02-19 18:20
![image](https://github.com/Leafwing-Studios/leafwing-input-manager/assets/22796024/285589dd-05b1-4b20-888f-8009c1ce7838)

I've identified the actual problem; it appears that some clashes from `get_clashes()` were missed.

Should be an easy fix.

**Comment by Shute052** [comment] 2024-02-19 18:51
![image](https://github.com/Leafwing-Studios/leafwing-input-manager/assets/22796024/10fa1bd5-d3c5-474f-84df-0632bd75be5a)

This seems like a detour; the issue doesn't appear to be in the `handle_clashes` function.

**Comment by Shute052** [comment] 2024-02-19 19:46
I've identified the actual problem; it appears that the `ActionState` doesn't get updated because the shorter clashed `ActionData` has been removed but it should be `ActionData::default()` (since #450).

## Relevant Code
```rust
// Before
pub fn handle_clashes(
    &self,
    action_data: &mut [ActionData],
    input_streams: &InputStreams,
    clash_strategy: ClashStrategy,
) {
    for clash in self.get_clashes(action_data, input_streams) {
        // Remove the action in the pair that was overruled, if any
        if let Some(culled_action) = resolve_clash(&clash, clash_strategy, input_streams) {
            action_data[culled_action.index()] = ActionData::default();
        }
    }
}

// After
pub fn handle_clashes(
    &self,
    action_data: &mut HashMap<A, ActionData>,
    input_streams: &InputStreams,
    clash_strategy: ClashStrategy,
) {
    for clash in self.get_clashes(action_data, input_streams) {
        // Remove the action in the pair that was overruled, if any
        if let Some(culled_action) = resolve_clash(&clash, clash_strategy, input_streams) {
            action_data.remove(&culled_action);
        }
    }
}
```

**Closed** 2024-02-19 21:24 UTC
Labels: bug
