### ISSUE TITLE
Multi Modal Input Maps. 

### ISSUE THREAD

**Issue by huhlig** [Leafwing-Studios/leafwing-input-manager#40] opened 2022-01-20 05:34 UTC
## What problem did the developer encounter?

Looking to use input mapping for a multiple modality game. The three modes my prototype offers are in states and are top-down flight, top-down tilemap, and a Grimrock style cellular 3d. Each mode has its own control scheme often sharing common keys for similar actions.

### Example
| Key   | Flying        | Walking   | Hacking     |
|-------|---------------|-----------|-------------|
| W     | Thrust        | MoveNorth | Advance     |
| A     | TurnLeft      | MoveWest  | RotateLeft  |
| S     | Reverse       | MoveSouth | Retreat     |
| D     | TurnRight     | MoveEast  | RotateRight |
| Q     | StrafeLeft    |           |             |
| E     | StrageRight   |           |             |
| Space | FirePrimary   |           |             |
| Alt   | FireSecondary |           |             |
| 1     | Slot1         | Slot1     | Slot1       |
| 2     | Slot2         | Slot2     | Slot2       |
| 3     | Slot3         | Slot3     | Slot3       |
| 4     | Slot4         | Slot4     | Slot4       |

## What was the fix?

Suggestion on Discord was to instantiate multiple copies of the plugin and create an enumeration for each game mode input map.

## How could this be better documented?

Currently undocumented.

**Comment by alice-i-cecile** [comment] 2022-01-27 22:33
Will be closed by #17.

**Comment by alice-i-cecile** [comment] 2022-01-27 22:34
Closing as a duplicate of #6 <3

**Closed by alice-i-cecile** 2022-01-27 22:34 UTC
Labels: documentation
