### ISSUE TITLE
Input value scaling

### ISSUE THREAD

**Issue by NiseVoid** [Leafwing-Studios/leafwing-input-manager#310] opened 2023-02-02 01:10 UTC
## What problem does this solve?

Registering dual axis mouse_motion and right_stick to the same action, like so:

```rust
commands.spawn(InputManagerBundle::<ControlAction> {
    action_state: ActionState::default(),
    input_map: InputMap::default()
        .insert(DualAxis::mouse_motion(), ControlAction::Camera)
        .insert(DualAxis::right_stick(), ControlAction::Camera)
        .build()
}
```
results in the mouse moving the camera at a way higher speed than the analog stick.

## What solution would you like?

A function on, or virtual input that can be wrapped around, the DualAxis to scale the values to something that's more on the same line. As a bonus this could also be used to set sensitivity in the input map per-device rather than globally.
The same would be useful on single axis inputs, like scrollwheel vs changing the camera by holding down a controller button. And possibly also non-axis values like gamepad triggers.

## What alternatives have you considered?

It's possible to bind them to separate Actions and scale them independantly in the system that rotates the camera. However, I feel like this would go against what this library tries to achieve.

## Related work

None that I could find

**Comment by alice-i-cecile** [comment] 2023-08-28 23:30
Closing as a duplicate of #322 :)

**Closed by alice-i-cecile** 2023-08-28 23:30 UTC
Labels: enhancement
