### ISSUE TITLE
Game crashes on startup when Bevy and LWIM's default features are disabled

### ISSUE THREAD

**Issue by NxSaken** [Leafwing-Studios/leafwing-input-manager#382] opened 2023-09-10 13:58 UTC
## Version
```
leafwing-input-manager = "0.10.0"
```

## Operating system & version

macOS 13.1

## What you did

1. Added `bevy` 0.11.2 with `default-features = false`
2. Added `leafwing-input-manager` 0.11 with `default-features = false`
3. Ran the app with `DefaultPlugins`.

## What you expected to happen

App launches and exits normally.

## What actually happened

App panics on startup:

```
thread 'main' panicked at 'Requested resource bevy_asset::asset_server::AssetServer does not exist in the `World`. 
                Did you forget to add it using `app.insert_resource` / `app.init_resource`? 
                Resources are also implicitly added via `app.add_event`,
                and can be added by plugins.', /Users/nurzhan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_asset-0.11.2/src/assets.rs:335:43
```

**Comment by 100-TomatoJuice** [comment] 2023-09-12 17:08
I found the cause of the error, at least part of it. When Bevy's default features are disabled, it does not create an `AssetServer`. Making LWIM, or the users project, depend on `bevy_asset` in `Cargo.toml` fixes the issue, but I still don't know the _exact_ reason for the error. "Where is LWIM asking for the `AssetServer`?" is the question I am still looking for.

**Comment by alice-i-cecile** [comment] 2023-09-12 17:20
Yeah, I don't think that's the right fix either. I genuinely don't see where we could be relying on bevy_assets directly ourselves. Does `bevy` with `DefaultPlugins` by itself crash with the exact feature set depended on by LWIM? We may have uncovered a bug upstream instead.

**Comment by 100-TomatoJuice** [comment] 2023-09-12 17:22
Oh, It does still crash!

**Comment by alice-i-cecile** [comment] 2023-09-12 17:24
Thanks for investigating this! Can you make an issue on the Bevy repo and link this issue for us?

**Comment by 100-TomatoJuice** [comment] 2023-09-12 17:24
It's the `serialize` feature that causes it. I can create an issue.

**Comment by alice-i-cecile** [comment] 2023-09-14 23:02
Fixed by https://github.com/bevyengine/bevy/pull/9803

**Closed by alice-i-cecile** 2023-09-14 23:02 UTC
Labels: bug, blocked
